name: Lint

on: [push]

jobs:

  lint:

    name: hadolint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: hadolint
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: ./3.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HADOLINT_ACTION_DOCKERFILE_FOLDER: ./3.8
